version: '3'

services:
  teamscale:
    image: 'cqse/teamscale:7.8.0'
    user: 1001:1001
    hostname: 'teamscale'
    restart: always
    working_dir: /var/teamscale
    volumes:
      - ./teamscale:/var/teamscale
      - ..:/bank
    ports:
      - "8080:8080"

