version: '3'

services:
  teamscale:
    image: 'cqse/teamscale:7.7.4'
    hostname: 'teamscale'
    restart: unless-stopped
    working_dir: /var/teamscale
    volumes:
      - ./teamscale:/var/teamscale
      - ../digitalbank-gen-one:/bank
    ports:
      - "8080:8080"

